application: cinnamonrolliov1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /_ah/(mapreduce|queue|warmup|start|stop).*
  script: cinnamonroll.wsgi.application
  login: admin
  secure: always

- url: /_ah/internalupload.*
  script: cinnamonroll.wsgi.application
  secure: always

- url: /static
  static_dir: static/
  secure: always

# Set Django admin to be login:admin as well as Django's is_staff restriction
- url: /admin.*
  script: cinnamonroll.wsgi.application
  secure: always
  login: admin

- url: /.*
  script: cinnamonroll.wsgi.application
  secure: always

skip_files:
    - manage.py
    - README.md
    - blah
    - install_deps
    - requirements.txt
    - sitepackages/dev*
    - \.storage.*
    - \.git
    - (.*)\.pyc
